### PR TITLE
Pull request for django-resume

### PR DESCRIPTION
**Pull request by aless80**
Hello, this is a pull request for your project. It was a good starting point for me to learn Django, but I had to rebuild it for modern Django (1.10.8) and python 3.5.2. Thanks

### CODE REVIEW

**Comment by ckelly** [comment]
hi @aless80!

Apologies for the delay, and thanks for the PR! Code looks pretty good!

quick question for you - any reason you changed the directory structure? Just curious more than anything.

**Comment by aless80** [comment]
Hi @ckelly ,
About the file structure I had the same question when I started hacking your project. When I decided to rebuild the project from scratch with standard commands I got the structure that you see in my version. Maybe you did the same in an old version of Django and things have changed. I am p-sure my structure reflects the recommended layout. For example, this links (and others) confirms that Django projects are basically
/myproj/
/myproj/manage.py
/myproj/myproj/*
/myproj/app/*

**Comment by aless80** [comment]
@bittner You mean I cannot edit the original README?

**Comment by ckelly** [comment]
hey @bittner @aless80 

apologies, I was working on getting some things verified, but it all escaped me again. heh. 

per previous discussion, I think the original idea was to have sub dirs to allow for testing, etc, but I don't think it's worth going back and reorganizing at this time. 

I'm going to approve and merge this, and I'll probably tweak a few things along the way (updated readme, contributors file, etc). 

@aless80 I'm also going to give you commit access to the repo, seeing as you did a ton of work here!

**Pull request merged**
